### ISSUE TITLE
GUI-Session interface

### ISSUE THREAD

**Issue by AlexsJones** [AlexsJones/whisper#30]
https://github.com/AlexsJones/whisper/blob/gui_interface/src/session/session.c

I've come up with this in gui_interface branch.

it should work for us hopefully.

The idea is from the gui you'd pass a pointer to a callback function for read (I give you session guid and the message).

before i return the message ill call internally `read_and_decrypt` from a polling thread inside of session to clean up the message.

What do you think?

**Comment by draganglumac** [comment]
I like the approach. But I might need to give you some kind of token for the GUI which you will pass into the read callback, otherwise we'll have to use globals which is not ideal.

That way if I pass you a token I can encapsulate the logic for wait and notify inside the gui. I suppose writing is not that much of an issue because that can be done from the GUI thread directly, so that bit can stay as it is.

I was playing round with the ideas of having blocking threads for this kinda stuff in jnxlibc, but haven't really come up a good generic solution yet.

I'll start plumbing the gui in this afternoon got some errands to run this morning.

**Comment by AlexsJones** [comment]
Yeah I think a token is going to be necessary definitely, maybe something the session can store

**Comment by AlexsJones** [comment]
https://github.com/AlexsJones/whisper/blob/gui_interface/src/net/secure_comms.c#L72

I've added a function pointer that can be overriden to redirect the session output. At the moment I'm defaulting a callback and evertyhing is working hunky dory
