### ISSUE TITLE
Hook up of code

### ISSUE THREAD

**Issue by AlexsJones** [AlexsJones/whisper#9]
Hi mate, I've come to a bit of a standstill here
https://github.com/AlexsJones/whisper/blob/session/src/app/main.c#L53

I've reworked the command line input system to take parameters, and I have a friendly name inputted by the user for a peer e.g.
```
> session AlexComputer
```

If I give the peerStore AlexComputer I hope it would return the peer via this method
```
peer *peerstore_lookup_with_name(peerstore *ps, char *name);
```

Anyway you could help me out here?

From the app context am I suppose to pull the peer store from the discovery service?

**Comment by draganglumac** [comment]
Yeah, when I originally designed the API I was gonna have a public key there instead of the name so I never bothered to make "lookup by name" function. I can certainly do that but of course there's no guarantees that a username will resolve to a unique peer (whereas with GUID it's for all intents and purposes unique). For example you can have the same username on multiple machines (multiple Alex's) so we'd have to introduce some smarts about making the name unique.

However, there's another way we can do this, which is what I hinted at in an earlier Skype chat. That your session service just expects to receive a peer object. Or alternatively it receives a guid for the selected name from the interface so that you can use that to look it up in the peerstore.

Generally a user would have to look up active peers before they connect (list command). So list command could actually keep the retrieved peer structs in the app space (like an array or a list or a hash or something) so that when the user selects "connect to a name" the UI would just pass the peer struct that it retrieved earlier in the list command.

If you can think of a better way I am open to suggestions.

The app.h and app.c are just dumping ground for anything that I use in main.c (so as not to clutter main.c) and I had no rhyme or reason to it. I am certainly not precious about whether we keep it or refactor it into different files or rename functions to be more organised.

I hope that helps

I'll be on Skype shortly.
